[package]
name = "backgammon"
version = "0.1.0"
authors = ["Nilan Marktanner <nilan.marktanner@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.7"
clap = "2.33.0"
prettytable-rs = "^0.8"
rand = "0.7.2"
